
server:
  port: 8082

spring:
  # 本机安装的mysql配置
  datasource:
    url: jdbc:mysql://localhost:3306/mall?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1220
  # redis配置
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000ms
  # kafka配置
#  kafka:
#    producer:
#      #指定kafka server的地址，集群配多个，中间，逗号隔开
#      bootstrap-servers: localhost:9092
#      retries: 1
#      # 每次批量发送消息数量
#      batch-size: 16384
#      buffer-memory: 40960
#      # 指定消息key和消息体的编解码方式
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      group-id: mall
#      enable-auto-commit: true
#      auto-offset-reset: latest
#      auto-commit-interval: 100
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    # 指定listener 容器中的线程数，用于提高并发量
#    listener:
#      concurrency: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml

# rabbitmq:
#  host: localhost
#  port: 5672
#  virtual-host: /mall # rabbitmq的虚拟host
#  username: mall
#  password: mall
#  publisher-confirms: ture

#自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间


# hadoop2.7.7 配置
#hadoop.name-node: hdfs://192.168.182.3:9000
#hadoop.namespace: /test1