
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1220
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml

rabbitmq:
  host: localhost
  port: 5672
  virtual-host: /mall # rabbitmq的虚拟host
  username: mall
  password: mall
  publisher-confirms: ture

#自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间
